// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_exam.Data;

#nullable disable

namespace Web_exam.Data.Migrations
{
    [DbContext(typeof(NonogramDbContext))]
    partial class NonogramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_exam.Models.Nonogram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nonograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = "Medium",
                            Name = "Harry Potter",
                            SolutionJson = "[[0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0],[0,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0],[0,1,0,0,0,0,1,0,0,1,1,1,1,0,0,0,0,0],[0,1,1,0,0,1,1,0,0,1,0,0,0,1,1,1,0,0],[0,0,1,0,0,1,1,0,0,1,1,0,0,0,0,0,1,1],[0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,1],[1,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1],[1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1],[1,1,1,0,0,0,1,0,0,1,1,0,0,1,1,0,0,1],[0,0,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1],[0,0,1,0,0,1,1,0,0,1,0,0,0,0,0,0,1,0],[0,0,1,0,0,1,1,0,0,1,0,0,0,1,1,1,1,0],[0,1,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,0],[0,1,1,1,1,1,0,0,0,0,1,0,0,1,0,0,0,0],[0,0,0,0,0,1,1,1,1,1,1,0,0,1,1,0,0,0],[0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0],[0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0]]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
